# Generated by Django 5.1.4 on 2024-12-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
    ]
